#!/bin/sh

# variables
curr_dir=`pwd`

dir=`dirname $0`
script_path=`cd  $dir;pwd`

database_path=${script_path}
propel_bin=${script_path}/../vendor/bin/propel
src_path=${script_path}/../src
backup_path=${script_path}/../backup
output_path=${database_path}/generated
sql_path=${database_path}/sql
config_path=${script_path}/../config
config_file=propel.php

# backing up
mkdir $backup_path
cp $src_path/model/User.php $backup_path/User.php

# running propel
cd $database_path
$propel_bin build --output-dir=$output_path
$propel_bin sql:build --output-dir=$sql_path
#$propel_bin convert-conf --output-dir=$config_path --output-file=$config_file

# copy files
cp -Rf $output_path/keeko/core/model $src_path/

# restore
cp -f $backup_path/User.php $src_path/model/User.php

# cleanup
rm -rf $output_path
rm -rf $backup_path
